### ISSUE TITLE
Release with 5.x govuk-frontend ?

### ISSUE THREAD

**Issue by stuaxocabinetoffice** [uktrade/govuk-frontend-django#50]
Govuk-frontend has a few releases in the 5.x series, will there be a corresponding govuk-frontend-django release ?

**Comment by CamLamb** [comment]
I'm just catching up on this project today and it looks like the scripts have auto created the PRs needed for this.
I'll take a look over these and try to get the relevant releases created and published

**Comment by CamLamb** [comment]
Marking this issue as completed as I have now released many versions of the project that include most of the latest 5.x updates:
https://github.com/uktrade/govuk-frontend-django?tab=readme-ov-file#compatibility-table

New releases today:
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.5.0 - govuk-frontend v5.1.0
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.5.1 - govuk-frontend v5.1.0
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.6.0 - govuk-frontend v5.2.0
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.7.0 - govuk-frontend v5.3.0
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.8.0 - govuk-frontend v5.3.1
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.9.0 - govuk-frontend v5.4.0
https://github.com/uktrade/govuk-frontend-django/releases/tag/0.9.1 - govuk-frontend v5.4.0

**Comment by stuaxo** [comment]
Awesome, cheers @CamLamb
